version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "5000:5000"
    command: >
      sh -c "
        pnpm install &&
        pnpm prisma migrate deploy &&
        pnpm run seed &&
        pnpm run start:prod
      "

volumes:
  pgdata:
